import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";
const translations: Record<string, Record<string, string>> = {
  vi: {
    "home.title": "Trang chủ",
    "home.welcome": "Chào mừng bạn, {name}!",
    "home.selectLanguage": "Chọn ngôn ngữ",
    "home.selectTheme": "Chọn giao diện",
    "home.light": "Sáng",
    "home.dark": "Tối",
    "home.auto": "Tự động",
    "home.ready": "Bạn đã sẵn sàng học hôm nay chưa?",
    "home.beginner": "Trình độ sơ cấp",
    "home.newLesson": "Bài học mới",
    "home.vietnameseAlphabet": "Bảng chữ cái tiếng Việt",
    "home.alphabetDesc":
      "Học 29 chữ cái và cách phát âm tiếng Việt. Bắt đầu hành trình chinh phục tiếng Việt.",
    "home.startLearning": "Bắt đầu học",
    "home.exploreMore": "Khám phá thêm",
    "home.pronunciation": "Luyện phát âm",
    "home.pronunciationDesc": "Luyện phát âm tiếng Việt với phản hồi AI.",
    "home.games": "Trò chơi tương tác",
    "home.gamesDesc": "Học tiếng Việt qua các trò chơi thú vị và hấp dẫn.",
    "profile.title": "Hồ sơ & Cài đặt",
    "profile.info": "Thông tin hồ sơ",
    "profile.editProfile": "Chỉnh sửa hồ sơ",
    "profile.language": "Ngôn ngữ ứng dụng",
    "profile.theme": "Chọn giao diện",
    "profile.darkMode": "Chế độ tối",
    "profile.security": "Bảo mật tài khoản",
    "profile.support": "Trung tâm hỗ trợ",
    "profile.logout": "Đăng xuất",
    "profile.logoutConfirm": "Bạn có chắc muốn đăng xuất không?",
    "profile.loggedOut": "Đã đăng xuất",
    "profile.changePassword": "Đổi mật khẩu",
    "profile.oldPassword": "Mật khẩu cũ",
    "profile.newPassword": "Mật khẩu mới",
    "profile.confirmPassword": "Xác nhận mật khẩu mới",
    "profile.save": "Lưu",
    "profile.cancel": "Hủy",
    "profile.name": "Tên",
    "profile.email": "Email",
    "profile.age": "Tuổi",
    "profile.logoutMessage": "Bạn có muốn đăng xuất không?",
    "profile.logoutSuccess": "Đăng xuất thành công",
    "profile.logoutSuccessMessage": "Bạn đã đăng xuất thành công.",
    "profile.on": "Bật",
    "profile.off": "Tắt",
    "lessons.title": "Bài học",
    "quizzes.title": "Trắc nghiệm",
    "dashboard.title": "Bảng điều khiển",
    "dashboard.welcome": "Chào mừng trở lại, {name}!",
    "dashboard.readyToManage": "Bạn đã sẵn sàng quản lý khóa học chưa?",
    "dashboard.teacher": "Giáo viên",
    "dashboard.quickLinks": "Liên kết nhanh",
    "dashboard.courses": "Khóa học",
    "dashboard.manageCourses": "Quản lý khóa học của bạn",
    "dashboard.students": "Học viên",
    "dashboard.trackProgress": "Theo dõi tiến trình học viên",
    "dashboard.quizzes": "Bài kiểm tra",
    "dashboard.createAndGrade": "Tạo và chấm điểm bài kiểm tra",
    "courses.title": "Khóa học",
    "students.title": "Học sinh",
    "communication.title": "Giao tiếp",
    "dashboard.selectLanguage": "Chọn ngôn ngữ",
    "dashboard.selectTheme": "Chọn giao diện",
    "dashboard.light": "Sáng",
    "dashboard.dark": "Tối",
  },

  en: {
    "home.title": "Home",
    "home.welcome": "Welcome back, {name}!",
    "home.selectLanguage": "Select Language",
    "home.selectTheme": "Select Theme",
    "home.light": "Light",
    "home.dark": "Dark",
    "home.auto": "Auto",
    "home.ready": "Are you ready to learn Vietnamese today?",
    "home.beginner": "Beginner Level",
    "home.newLesson": "New Lesson",
    "home.vietnameseAlphabet": "Vietnamese Alphabet",
    "home.alphabetDesc":
      "Learn all 29 Vietnamese letters and pronunciation. Start your journey to mastering Vietnamese.",
    "home.startLearning": "Start Learning",
    "home.exploreMore": "Explore More",
    "home.pronunciation": "Pronunciation Practice",
    "home.pronunciationDesc":
      "Master Vietnamese pronunciation with AI feedback.",
    "home.games": "Interactive Games",
    "home.gamesDesc": "Learn Vietnamese through fun and engaging games.",
    "profile.title": "Profile & Settings",
    "profile.info": "Profile Info",
    "profile.editProfile": "Edit Profile",
    "profile.language": "App Language",
    "profile.theme": "Select Theme",
    "profile.darkMode": "Dark Mode",
    "profile.security": "Account Security",
    "profile.support": "Support Center",
    "profile.logout": "Logout",
    "profile.logoutConfirm": "Are you sure you want to logout?",
    "profile.loggedOut": "Logged out",
    "profile.changePassword": "Change Password",
    "profile.oldPassword": "Old Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.save": "Save",
    "profile.cancel": "Cancel",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.age": "Age",
    "profile.logoutMessage": "Do you want to logout?",
    "profile.logoutSuccess": "Logout successful",
    "profile.logoutSuccessMessage": "You have successfully logged out.",
    "profile.on": "On",
    "profile.off": "Off",
    "lessons.title": "Lessons",
    "quizzes.title": "Quizzes",
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back, {name}!",
    "dashboard.readyToManage": "Are you ready to manage courses?",
    "dashboard.teacher": "Teacher",
    "dashboard.quickLinks": "Quick Links",
    "dashboard.courses": "Courses",
    "dashboard.manageCourses": "Manage your courses",
    "dashboard.students": "Students",
    "dashboard.trackProgress": "Track student progress",
    "dashboard.quizzes": "Quizzes",
    "dashboard.createAndGrade": "Create and grade quizzes",
    "dashboard.selectLanguage": "Select Language",
    "dashboard.selectTheme": "Select Theme",
    "dashboard.light": "Light",
    "dashboard.dark": "Dark",
    "courses.title": "Courses",
    "students.title": "Students",
    "communication.title": "Communication",
  },

  ko: {
    "home.title": "홈",
    "home.welcome": "환영합니다, {name}님!",
    "home.selectLanguage": "언어 선택",
    "home.selectTheme": "테마 선택",
    "home.light": "라이트",
    "home.dark": "다크",
    "home.auto": "자동",
    "home.ready": "오늘 베트남어 학습을 준비하셨나요?",
    "home.beginner": "초급 레벨",
    "home.newLesson": "새로운 레슨",
    "home.vietnameseAlphabet": "베트남어 알파벳",
    "home.alphabetDesc":
      "베트남어 29글자와 발음을 배우고, 베트남어 마스터 여정을 시작하세요.",
    "home.startLearning": "학습 시작",
    "home.exploreMore": "더 알아보기",
    "home.pronunciation": "발음 연습",
    "home.pronunciationDesc": "AI 피드백으로 베트남어 발음을 마스터하세요.",
    "home.games": "인터랙티브 게임",
    "home.gamesDesc": "재미있고 흥미로운 게임으로 베트남어를 배우세요.",
    "profile.title": "프로필 및 설정",
    "profile.info": "프로필 정보",
    "profile.editProfile": "프로필 편집",
    "profile.language": "앱 언어",
    "profile.theme": "테마 선택",
    "profile.darkMode": "다크 모드",
    "profile.security": "계정 보안",
    "profile.support": "지원 센터",
    "profile.logout": "로그아웃",
    "profile.logoutConfirm": "정말 로그아웃 하시겠습니까?",
    "profile.loggedOut": "로그아웃 되었습니다",
    "profile.changePassword": "비밀번호 변경",
    "profile.oldPassword": "기존 비밀번호",
    "profile.newPassword": "새 비밀번호",
    "profile.confirmPassword": "새 비밀번호 확인",
    "profile.save": "저장",
    "profile.cancel": "취소",
    "profile.name": "이름",
    "profile.email": "이메일",
    "profile.age": "나이",
    "profile.logoutMessage": "로그아웃 하시겠습니까?",
    "profile.logoutSuccess": "로그아웃 성공",
    "profile.logoutSuccessMessage": "정상적으로 로그아웃 되었습니다.",
    "profile.on": "켜기",
    "profile.off": "끄기",
    "lessons.title": "레슨",
    "quizzes.title": "퀴즈",
    "dashboard.title": "대시보드",
    "dashboard.welcome": "환영합니다, {name}님!",
    "dashboard.readyToManage": "코스를 관리할 준비가 되었나요?",
    "dashboard.teacher": "강사",
    "dashboard.quickLinks": "빠른 링크",
    "dashboard.courses": "강좌",
    "dashboard.manageCourses": "강좌 관리",
    "dashboard.students": "학생",
    "dashboard.trackProgress": "학생 진행 상황 추적",
    "dashboard.quizzes": "퀴즈",
    "dashboard.createAndGrade": "퀴즈 생성 및 채점",
    "dashboard.selectLanguage": "언어 선택",
    "dashboard.selectTheme": "테마 선택",
    "dashboard.light": "라이트",
    "dashboard.dark": "다크",
    "courses.title": "코스",
    "students.title": "학생",
    "communication.title": "커뮤니케이션",
  },

  ja: {
    "home.title": "ホーム",
    "home.welcome": "おかえりなさい、{name}さん！",
    "home.selectLanguage": "言語選択",
    "home.selectTheme": "テーマ選択",
    "home.light": "ライト",
    "home.dark": "ダーク",
    "home.auto": "自動",
    "home.ready": "今日はベトナム語を学ぶ準備はできましたか？",
    "home.beginner": "初級レベル",
    "home.newLesson": "新しいレッスン",
    "home.vietnameseAlphabet": "ベトナム語アルファベット",
    "home.alphabetDesc":
      "ベトナム語の29文字と発音を学びましょう。ベトナム語マスターへの旅を始めましょう。",
    "home.startLearning": "学習開始",
    "home.exploreMore": "もっと探検",
    "home.pronunciation": "発音練習",
    "home.pronunciationDesc":
      "AIフィードバックでベトナム語発音をマスターしましょう。",
    "home.games": "インタラクティブゲーム",
    "home.gamesDesc": "楽しく魅力的なゲームでベトナム語を学びましょう。",
    "profile.title": "プロフィールと設定",
    "profile.info": "個人情報",
    "profile.editProfile": "プロフィールを編集",
    "profile.language": "アプリの言語",
    "profile.theme": "テーマを選択",
    "profile.darkMode": "ダークモード",
    "profile.security": "アカウントのセキュリティ",
    "profile.support": "サポートセンター",
    "profile.logout": "ログアウト",
    "profile.logoutConfirm": "本当にログアウトしますか？",
    "profile.loggedOut": "ログアウトしました。",
    "profile.changePassword": "パスワードを変更",
    "profile.oldPassword": "古いパスワード",
    "profile.newPassword": "新しいパスワード",
    "profile.confirmPassword": "新しいパスワードを確認",
    "profile.save": "保存",
    "profile.cancel": "キャンセル",
    "profile.name": "名前",
    "profile.email": "メールアドレス",
    "profile.age": "年齢",
    "profile.logoutMessage": "ログアウトしてもよろしいですか？",
    "profile.logoutSuccess": "ログアウトしました",
    "profile.logoutSuccessMessage": "正常にログアウトされました。",
    "profile.on": "オン",
    "profile.off": "オフ",
    "lessons.title": "レッスン",
    "quizzes.title": "クイズ",
    "dashboard.title": "ダッシュボード",
    "dashboard.welcome": "{name}さん、おかえりなさい！",
    "dashboard.readyToManage": "コースを管理する準備はできていますか？",
    "dashboard.teacher": "教師",
    "dashboard.quickLinks": "クイックリンク",
    "dashboard.courses": "コース",
    "dashboard.manageCourses": "コースを管理する",
    "dashboard.students": "学生",
    "dashboard.trackProgress": "学生の進捗を追跡",
    "dashboard.quizzes": "クイズ",
    "dashboard.createAndGrade": "クイズの作成と採点",
    "dashboard.selectLanguage": "言語を選択",
    "dashboard.selectTheme": "テーマを選択",
    "dashboard.light": "ライト",
    "dashboard.dark": "ダーク",
    "courses.title": "コース",
    "students.title": "学生",
    "communication.title": "コミュニケーション",
  },
  zh: {
    "home.title": "首页",
    "home.welcome": "欢迎回来，{name}！",
    "home.selectLanguage": "选择语言",
    "home.selectTheme": "选择主题",
    "home.light": "浅色",
    "home.dark": "深色",
    "home.auto": "自动",
    "home.ready": "准备好今天学习越南语了吗？",
    "home.beginner": "初级水平",
    "home.newLesson": "新课",
    "home.vietnameseAlphabet": "越南语字母表",
    "home.alphabetDesc": "学习越南语29个字母及其发音。开始您的越南语掌握之旅。",
    "home.startLearning": "开始学习",
    "home.exploreMore": "探索更多",
    "home.pronunciation": "发音练习",
    "home.pronunciationDesc": "通过AI反馈掌握越南语发音。",
    "home.games": "互动游戏",
    "home.gamesDesc": "通过有趣且引人入胜的游戏学习越南语。",
    "profile.title": "个人资料与设置",
    "profile.info": "个人信息",
    "profile.editProfile": "编辑资料",
    "profile.language": "应用语言",
    "profile.theme": "选择主题",
    "profile.darkMode": "深色模式",
    "profile.security": "账户安全",
    "profile.support": "帮助中心",
    "profile.logout": "退出登录",
    "profile.logoutConfirm": "确定要退出登录吗？",
    "profile.loggedOut": "您已退出账户。",
    "profile.changePassword": "更改密码",
    "profile.oldPassword": "旧密码",
    "profile.newPassword": "新密码",
    "profile.confirmPassword": "确认新密码",
    "profile.save": "保存",
    "profile.cancel": "取消",
    "profile.name": "姓名",
    "profile.email": "电子邮箱",
    "profile.age": "年龄",
    "profile.logoutMessage": "确定要登出吗？",
    "profile.logoutSuccess": "已登出",
    "profile.logoutSuccessMessage": "您已成功登出。",
    "profile.on": "开启",
    "profile.off": "关闭",
    "lessons.title": "课程",
    "quizzes.title": "测验",
    "dashboard.title": "仪表板",
    "dashboard.welcome": "欢迎回来，{name}！",
    "dashboard.readyToManage": "准备管理您的课程吗？",
    "dashboard.teacher": "教师",
    "dashboard.quickLinks": "快捷链接",
    "dashboard.courses": "课程",
    "dashboard.manageCourses": "管理您的课程",
    "dashboard.students": "学生",
    "dashboard.trackProgress": "跟踪学生进度",
    "dashboard.quizzes": "测验",
    "dashboard.createAndGrade": "创建和评分测验",
    "dashboard.selectLanguage": "选择语言",
    "dashboard.selectTheme": "选择主题",
    "dashboard.light": "浅色",
    "dashboard.dark": "深色",
    "courses.title": "课程",
    "students.title": "学生",
    "communication.title": "通讯",
  },
};

interface LanguageContextProps {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: "vi",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<string>("vi");

  useEffect(() => {
    const loadLanguage = async () => {
      const savedLang = await AsyncStorage.getItem("appLanguage");
      if (savedLang) setLanguageState(savedLang);
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: string) => {
    setLanguageState(lang);
    await AsyncStorage.setItem("appLanguage", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
